### ISSUE TITLE
Launch jobs with user accounts

### ISSUE THREAD

**Issue by arthursw** [mpc-bioinformatics/nf-cloud#9]
Hello,
I am wondering whether it is possible for the Worker service to launch NextFlow jobs with user accounts (as if the user connects with ssh and launches a job himself). This is important so that user get their real SLURM permissions and quotas.
I suppose you had this idea? Do you think it would be feasible?
Thanks! And thank you for developing and open-sourcing this excellent application.

**Comment by arthursw** [comment]
Thanks for you answer! I was hoping there might be something possible by specifying the user credentials in the [clusterOptions](https://www.nextflow.io/docs/latest/process.html#process-clusteroptions) of the SLURM executor of NextFlow, but I guess it's not really that easy. So I am considering developing a similar app where the workers would call the SLURM REST API directly, without Nextflow ; but this is very hypothetical for now... Thanks anyway

**Comment by di-hardt** [comment]
Ahh sorry. This was a missunderstanding, I thougt the user needed to something natively installed.   
You should be able to use the `clusterOption`. I'm using the [`container`](https://www.nextflow.io/docs/latest/process.html#container) option in most of my workflows and enable the use of Docker via a profile in my `nextflow.config`.

**Comment by arthursw** [comment]
Ok, thanks!
